services:
  db:
    image: postgres:alpine
    container_name: issa_portfolio_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - issa_portfolio-network
    restart: always

  api:
    env_file: .env
    image: issa_portfolio:latest
    container_name: issa_portfolio_api
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - issa_portfolio-network
    ports:
      - 5000:5000
    restart: always

networks:
  issa_portfolio-network:
