FROM node:14-slim

WORKDIR /app

COPY package.json yarn.lock ./

WORKDIR /usr/src/app

RUN yarn global add @nestjs/cli@7.6.0

COPY package.json yarn.lock ./

RUN yarn

COPY . .

ENV NODE_ENV=development

CMD yarn start:dev
